version: '2'
services:
  bidemo-influx-db:
    image: influxdb
    container_name: bidemo-influx-db
    ports:
      - 8086:8086
    networks:
      - bidemo-influxdb-network
  bidemo-influx-grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - bidemo-influxdb-network
    depends_on:
      - bidemo-influx-db

networks:
  bidemo-influxdb-network:
    driver: bridge