version: '3.4'

services:
  bidemo-elk-es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.minimum_master_nodes: 1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
    networks:
      - bidemo-elk-network
  bidemo-elk-logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.4.2
    volumes:
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: ./logstash/sampledata
        target: /usr/share/sampledata
        read_only: true
    ports:
      - 9600:9600
    networks:
      - bidemo-elk-network
    depends_on:
      - bidemo-elk-es
  bidemo-elk-kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.4.2
    environment:
      ELASTICSEARCH_URL: http://bidemo-elk-es:9200
    ports:
      - 5601:5601
    networks:
      - bidemo-elk-network
    depends_on:
      - bidemo-elk-es

networks:
  bidemo-elk-network:
    driver: bridge